### ISSUE TITLE
Update user interface for Phase 2 functionality

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#372]
> Updating web user interface following completion 
of Phase 2 functions.

This will include updating the UI to:

- [ ] Include the cohesive network results #209 
- [ ] Include data on street space (if we can find a way to publish widths data) #370 
- [ ] Cycling by design compliance data (compliant or not for each segment) #324

**Comment by mvl22** [comment]
Looks like these are all data to be generated. Is there a timescale for delivery of these?

**Comment by Robinlovelace** [comment]
> Looks like these are all data to be generated. Is there a timescale for delivery of these?

We should have the cohesive network results by end of this month, data on street space by mid Feb and cycling by compliance data by end of Feb. Heads-up @wangzhao0217 who is leading on the data processing, sound doable to you Zhao?
